### ISSUE TITLE
VYZN: Viewer: Selection of one or more elements

### ISSUE THREAD

**Issue by Adrian62D** [bldrs-ai/Share#380]
One or more elements of the model can be selected by the user.

Behavior:
- Shift+ double click to add or remove item from current selection
- pressing escape will deselect all, (in addition to "A" which already existed)
- selecting multiple elements will now also update the propeties window and navigation to be for the last selected element
- multiple selection will update the expanded/highlighted tree items

Fits to product strategy: yes
Potentially Dec/Jan

**Comment by MarkusSteinbrecher** [comment]
@Adrian62D here too, how is this different to #475 ?

**Comment by Adrian62D** [comment]
#475 is about allowing the user to actually filter through the elements.

In BimCollab this functionality is called SmartViews:
https://www.bimcollab.com/en/products/bimcollab-zoom/smart-views

**Comment by OlegMoshkovich** [comment]
Does this issue include selecting multiple elements in the viewport and the tree?

**Comment by Adrian62D** [comment]
This issue covers:
- viewport (mouse)
- programmatic access via matrix

The tree view is covered in #417.
Should we merge these two issues?

**Comment by OlegMoshkovich** [comment]
![Image](https://user-images.githubusercontent.com/3433606/211810316-8856cb2b-c9ed-4bf3-aaf5-a8ea11abe082.png)

**Comment by Adrian62D** [comment]
@OlegMoshkovich Based on our last discussion we should provide smaller, isolated PR's. Accordingly I've updated the description of this issue to change the scope to viewport only - without programmatic access. The PR for the implementation follows shortly.

- Programmatic access (matrix widget api) has now been split to: #541.
- Has there already been an issue created for the selection-sets idea? This should be splitted as well.

**Comment by OlegMoshkovich** [comment]
I assumed the point of selecting multiple elements is to control the visibility of what is selected.

**Comment by pablo-mayrgundter** [comment]
We're having a design discussion in this thread:

https://discord.com/channels/853953158560743424/1063129406563950682

We're thinking to have some local lookup tables in a state file stored in the client and serialize around matrix.  This will reference IFC UUIDs and expressIDs as serialized at a particular version of the model.  If the client sees a changed model version or changed state file version, they rebuild from scratch.  Otherwise, we'll have some ability to use the IDs stored in the table as stable keys for shared state between clients.

**Comment by OlegMoshkovich** [comment]
@Adrian62D is this issue done?

**Comment by Adrian62D** [comment]
Remaining work covered in #548
