### ISSUE TITLE
Color mapping support

### ISSUE THREAD

**Issue by Adrian62D** [bldrs-ai/Share#387]
Color mappings for values found in the attributes can be defined (“heatmap”) by the user and also programmatically.

(ok if restricted to admin in the beginning)

**Comment by MarkusSteinbrecher** [comment]
how is this different to [383](https://github.com/bldrs-ai/Share/issues/383)?

**Comment by rti-vyzn** [comment]
> how is this different to [383](https://github.com/bldrs-ai/Share/issues/383)?

I'm not entirely sure if I understand the issue correctly, but I know that in other viewers (e.g. xeokit) you can pre-assign colours to different IFC types, in order to get them right in the first render. 

Otherwise I'm not entirely sure if the entire scene would have to be in place in order to assign colours to specific elements - meaning it would not have the desired colours from the beginning. 

But maybe this is not what we're talking about, I don't know.

**Comment by Adrian62D** [comment]
Sorry, this is a duplicate, you may close it.
